### ISSUE TITLE
missing mopify-spotify in image

### ISSUE THREAD

**Issue by ghost** [Whhoesj/docker-mopidy#1]
hoi,

Heb je image gebruikt maar mis de mopify-spotify extention.
Verder zag ik dat je snap-server uitgecomment had. Zal eens kijken of ik hem aan de praat krijg. 
Zal ik hem mergen?

**Comment by Whhoesj** [comment]
Ga je gang!
Snapcast heeft een tijd terug gewerkt (https://github.com/Whhoesj/docker-mopidy/commit/5fbfe9c947efa2264044db5c0dfbf3dd4b4b3cf9). De client ervoor heb ik buiten Docker om gedraaid. Alleen de server zit erin.

**Comment by ghost** [comment]
Tja. Had het ff werkend maar krijg resync conflicts tussen cliënt en server..

**Comment by Whhoesj** [comment]
Mopify is toegevoegd

**Comment by Whhoesj** [comment]
Snapcast is te volgen in #2
